"""initial_schema

Revision ID: 56cb979957d6
Revises: 
Create Date: 2026-05-21 17:42:52.292856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cb979957d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    op.execute("""
                    CREATE OR REPLACE FUNCTION generate_short_id()
                    RETURNS TEXT AS $$
                    DECLARE
                        chars TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
                        result TEXT := '';
                        i INTEGER := 0;
                        byte BYTEA;
                    BEGIN
                        byte := gen_random_bytes(10);
                        FOR i IN 1..10 LOOP
                            result := result || substr(chars, (get_byte(byte, i-1) % 36) + 1, 1);
                        END LOOP;
                        RETURN 'REQ-' || result;
                    END;
                    $$ LANGUAGE plpgsql VOLATILE;
                    """)

    op.execute("""
                CREATE OR REPLACE FUNCTION update_updated_at_column()
                RETURNS TRIGGER AS $$
                BEGIN
                    NEW.updated_at = NOW();
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                """)

    op.execute("""
                CREATE OR REPLACE FUNCTION update_answered_at()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.answer IS NOT NULL AND OLD.answer IS NULL THEN
                        NEW.answered_at = NOW();
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                """)

    op.create_table('users',
    sa.Column('max_user_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=True),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('max_user_id'),
    schema='bot_schema'
    )
    op.create_table('requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('short_id', sa.String(length=20), server_default=sa.text('generate_short_id()'), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('visit_time', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('initiator_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['bot_schema.users.max_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_id'),
    schema='bot_schema'
    )
    op.execute("""
                    CREATE TRIGGER trigger_update_requests_updated_at
                        BEFORE UPDATE ON bot_schema.requests
                        FOR EACH ROW
                        EXECUTE FUNCTION update_updated_at_column();
                    """)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['bot_schema.users.max_user_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['bot_schema.requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bot_schema'
    )
    op.create_table('clarifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('asked_by', sa.String(length=255), nullable=False),
    sa.Column('asked_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asked_by'], ['bot_schema.users.max_user_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['bot_schema.requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bot_schema'
    )
    op.execute("""
                    CREATE TRIGGER trigger_update_clarifications_answered_at
                        BEFORE UPDATE ON bot_schema.clarifications
                        FOR EACH ROW
                        EXECUTE FUNCTION update_answered_at();
                    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS trigger_update_requests_updated_at ON bot_schema.requests')
    op.execute('DROP TRIGGER IF EXISTS trigger_update_clarifications_answered_at ON bot_schema.clarifications')

    op.drop_table('clarifications', schema='bot_schema')
    op.drop_table('audit_log', schema='bot_schema')
    op.drop_table('requests', schema='bot_schema')
    op.drop_table('users', schema='bot_schema')

    op.execute('DROP FUNCTION IF EXISTS update_updated_at_column()')
    op.execute('DROP FUNCTION IF EXISTS update_answered_at()')
    op.execute('DROP FUNCTION IF EXISTS generate_short_id()')
    # ### end Alembic commands ###
