"""initial_schema

Revision ID: f20f78c67a2d
Revises: 
Create Date: 2026-05-20 01:40:10.045869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20f78c67a2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('max_user_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=True),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('max_user_id'),
    schema='bot_schema'
    )
    op.create_table('requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('visit_time', sa.String(length=50), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'need_clarification', 'closed', name='request_status'), nullable=False),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('clarification_question', sa.Text(), nullable=True),
    sa.Column('clarification_answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('initiator_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['bot_schema.users.max_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bot_schema'
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['bot_schema.requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bot_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log', schema='bot_schema')
    op.drop_table('requests', schema='bot_schema')
    op.drop_table('users', schema='bot_schema')
    # ### end Alembic commands ###
